### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by petriinap** [maaz15/adahomeworks#2]
I would have experimented with some other plot types as well such as pie plots or box plots (to illustrate variance and deviation) for example in case of ticket price, which was not plotted.

**Comment by e-bug** [comment]
I agree with you, different plots might give better representations.
Due to the large amount of information in the Titanic exercise, we focused on the key elements related to the 'survival' theme, i.e. we didn't think ticket price played a key role in this context.

Thanks for your feedback, we appreciated that!
