### ISSUE TITLE
Review Homework 1

### ISSUE THREAD

**Issue by vfaramond** [maaz15/adahomeworks#3]
Hey guys, good job for the Homework, you explained your code very well before and after the exercises, keep doing this !

However, some remarks:

**Intro to Pandas**
- Exercise 2
  - There is a more "time-efficient" way to do it `data[(data.phylum.str.endswith('bacteria')) & (data.value > 1000)]`.
- Exercise 3
  - Using `.sum()` on a mask to get the number of rows with the given condition is not the more natural way for me to do it, I would use `baseball[lan_sfn_query].shape[0]` or `len(baseball[lan_sfn_query].index)`.
- Ebola exercise
  - I would invert the index, i.e. `Date, Country` instead of `Country, Date` in order to compare different countries at the same date, like this :

<img width="348" alt="screen shot 2016-10-06 at 19 18 31" src="https://cloud.githubusercontent.com/assets/9916213/19162821/ba030d72-8bf9-11e6-837c-e2404b4d0482.png">

**Data Wrangling with Pandas**
- Titanic
  - Part 1
    - No comments and analysis of the results (numbers, plots and correlation)
    - What about `fare`, `sibsp`, `parch` and `fare` ?
  - Part 3
    - The plot is not readable, as there are two plots on the same figure. You can use `matplotlib.pyplot.figure()` in order to plot the second one on a new figure ;)

**Comment by dmartr** [comment]
I do agree with my partner. The code is really well documented, each step is perfectly explained and the solution is really easy to follow and understand. 

I have no more remarks to make. 

Very good job!

**Comment by e-bug** [comment]
Hi guys, thanks for spending some time giving us your feedback!

In the Ebola exercise we provided a view that allows us to see how the infection spread through each country. Of course, using your representation would have given us different insights, such as the propagation in the different countries day by day. There was no specific representation in the assignment, and so we ended up with a country-level view.

In the Titanic, indeed, providing more details and statistics would have allowed us drawing better conclusions. Thanks!
We didn't plot every attribute of the schema because they are a lot. We just focused on the ones which are more relevant to the 'survival' theme of the assignment.

We actually wanted to overlap the graphs to compare the number of survived people (by class and sex) with the total number of people. For instance, you can easily see that almost all women in first class survived! Perhaps, a more detailed explanation would have helped. 
We'll try to do better next time, thanks for your suggestions :)
